<?php

/**
 * @file
 * Contains app.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function app_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the app module.
    case 'help.page.app':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function app_theme() {
  return [
    'app' => [
      'template' => 'app',
      'render element' => 'children',
    ],
  ];
}
