<?php

/**
 * @file
 * Contains php4logger.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function php4logger_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the php4logger module.
    case 'help.page.php4logger':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function php4logger_theme() {
  return [
    'php4logger' => [
      'template' => 'php4logger',
      'render element' => 'children',
    ],
  ];
}
